# Generated by Django 3.1.6 on 2021-06-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dungeons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='is_official',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='DungeonRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('is_entrance', models.BooleanField(default=False)),
                ('is_exit', models.BooleanField(default=False)),
                ('room_text', models.TextField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms',
                                              to='dungeons.dungeon')),
            ],
            options={
                'unique_together': {('dungeon', 'slug'), ('dungeon', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DungeonPathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                  to='dungeons.dungeonroom')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths',
                                             to='dungeons.dungeonroom')),
            ],
        ),
    ]
