# Generated by Django 3.1.6 on 2021-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cmdrjump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderjumpstartentry',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
