# Generated by Django 3.1.6 on 2021-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cmdrjump', '0002_commanderjumpstartentry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderjumpstartentry',
            name='category',
            field=models.CharField(
                choices=[('C', 'Creature'), ('P', 'Planeswalker'), ('S', 'Sorcery'), ('I', 'Instant'),
                         ('A', 'Artifact'), ('E', 'Enchantment'), ('L', 'Land'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='dualcoloredentry',
            name='category',
            field=models.CharField(
                choices=[('C', 'Creature'), ('P', 'Planeswalker'), ('S', 'Sorcery'), ('I', 'Instant'),
                         ('A', 'Artifact'), ('E', 'Enchantment'), ('L', 'Land'), ('U', 'Unknown')], max_length=1),
        ),
    ]
