# Generated by Django 3.1.5 on 2021-02-13 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_printing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('default_pack_count', models.IntegerField(default=3)),
                ('default_pack_size', models.IntegerField(default=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CubeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.printing')),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cubes.cube')),
            ],
        ),
    ]
