# Generated by Django 3.1.6 on 2021-02-21 14:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cubes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cube',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
