# Generated by Django 3.1.6 on 2021-03-01 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cubes', '0002_auto_20210221_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cubeentry',
            old_name='card',
            new_name='printing',
        ),
    ]
