# Generated by Django 3.1.6 on 2021-02-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0002_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicset',
            name='printings',
            field=models.ManyToManyField(through='cards.Printing', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='printing',
            name='magic_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.magicset'),
        ),
    ]
