# Generated by Django 3.1.6 on 2021-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0004_auto_20210218_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
