# Generated by Django 3.1.6 on 2021-02-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0005_auto_20210225_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
