# Generated by Django 3.1.6 on 2021-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0006_auto_20210225_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='image_url',
            field=models.URLField(
                default='https://c1.scryfall.com/file/scryfall-cards/large/front/e/c/ec8e4142-7c46-4d2f-aaa6-6410f323d9f0.jpg?1561851198'),
            preserve_default=False,
        ),
    ]
