# Generated by Django 3.1.6 on 2021-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0007_printing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
