# Generated by Django 3.1.6 on 2021-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0009_auto_20210520_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
