# Generated by Django 3.1.6 on 2021-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0011_auto_20210523_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
