# Generated by Django 3.1.6 on 2021-02-21 14:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drafts', '0004_auto_20210221_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='draftcard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
