# Generated by Django 3.1.6 on 2021-02-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0007_printing_image_url'),
        ('drafts', '0005_auto_20210221_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card'),
        ),
        migrations.AddField(
            model_name='draftcard',
            name='printing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.printing'),
        ),
    ]
