# Generated by Django 3.1.6 on 2021-03-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0007_printing_image_url'),
        ('drafts', '0006_auto_20210227_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField(default=1)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.draftseat')),
            ],
        ),
        migrations.AlterField(
            model_name='draftcard',
            name='seat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='drafts.draftseat'),
        ),
        migrations.CreateModel(
            name='PackEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries',
                                           to='drafts.pack')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.printing')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.printing')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks',
                                           to='drafts.draftseat')),
            ],
        ),
    ]
