# Generated by Django 3.1.6 on 2021-03-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drafts', '0008_auto_20210301_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs',
                                    to='drafts.draftseat'),
        ),
    ]
