# Generated by Django 3.1.6 on 2021-03-01 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('drafts', '0009_auto_20210301_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpack',
            name='draft',
        ),
        migrations.DeleteModel(
            name='DraftCard',
        ),
        migrations.DeleteModel(
            name='DraftPack',
        ),
    ]
